//user
export const STATUS = "Active"
export const STUDENT_ROLE = "student"
export const ROLE_ID = 6
export const STATUS_REGISTERED = "registered"
export const USER_PROFILE_IMAGE_URL_PATH = "/default-image.avif"
export const CONTRIBUTOR_ROLE_ID = 3
//
export const PASSWORD = "adhyayan"
export const COMPANY = "Adhyayan NextGen Solutions Pvt. Ltd." 
export const SHORT_FORM = "AOPC"
export const RAZORPAY_KEY = "rzp_live_vTH9iKzUiECb9F"
export const WHATSAPP_PHONE = "+918750779557"
export const CURRENCY = "INR"
export const ADMISSION_PREFIX = "Adhyayan"
export const DOCUMENT_IMAGE_PATH = "public/uploads/"
export const CONTACT_PHONE_NO = "+91-9522933330"
export const CONTACT_EMAIL ="info@adhyayan.online"
export const SITE_URL_ONLINE ="adhyayan.online"
export const SITE_URL_ACADEMY ="aitm.academy"
export const SITE_URL_COMPANY ="angspl.com"
export const YOUTUBE_CHANNER_URL = "https://www.youtube.com/@adhyayan.online"
export const FULL_ADDRESS ="Gr. Floor, Kushwaha Complex, Ratibad road, Needbad Chauraha,Bhopal-462044, India "
export const HO_FULL_ADDRESS ="H.N. 301D4, Tulip Petals, GariHarsharu, Sector 89, Gurugram. Haryana-122505, India "
export const HO_ADDRESS1 ="H.N. 301D4, Tulip Petals,"
export const HO_ADDRESS2 ="GariHarsharu, Sector 89, "
export const HO_ADDRESS3 ="Gurugram. Haryana-122505, India "
export const ADDRESS1 =" Gr. Floor, Kushwaha Complex,"
export const ADDRESS2 ="Ratibad road, Needbad Chauraha,"
export const ADDRESS3 ="Bhopal-462044, India"
export const FIRST_NAME_LENGTH =20
export const LAST_NAME_LENGTH =20
export const DOB_YEAR_NUM =5
export const DOB_YEAR ='year'
export const DATE_OF_BIRTH2 ="1950-01-01"
export const ADMISSION_MONTH_NUM =1
export const ADMISSION_DATE_MONTH ='month'
export const EMAIL_LENGTH = 40
export const ADDRESS_LENGTH = 70
export const ZIP_CODE_LENGTH = 6
export const SCHOOL_NAME_LENGTH = 40
export const PERCENTAGE_LOWER = 33
export const PERCENTAGE_HIGHEST = 99
export const PASSWORD_MIN_LENGTH = 4
export const PASSWORD_MAX_LENGTH = 100
export const USER_NAME_LENGTH = 25
export const COURSE_NAME_LENGTH = 40
export const CODE_LENGTH = 8
export const DURATION_LENGTH = 12
export const CODE_PROJECT_TITLE_LENGTH =30
export const STUDY_NOTES_TITLE_LENGTH =40
export const IS_CLOUD_STORAGE_ENABLED =false
export const VIDEO_TITLE_LENGTH =50
export const VIDEO_TAGS_LENGTH =40
export const COMPANY_NAME_LENGTH = 50
export const PHONE_NO_LENGTH = 10
export const DEFAULT_COMPANY_ID = 1

export const PAY_FOR_COMPANY_SUBSCRIPTION = "Company Subscription"
export const PAY_MODE = "Online"
export const STATUS_PAID = "Paid"
export const SOURCE_FLAG_MISCELLANEOUS = "Miscellaneous"
export const SOURCE_FLAG_PUBLIC = "Public"